config/routes.rb
Rails.application.routes.draw do

get 'details/showpdf'
get 'particulars/pdfindex'
get 'details/showlast'
root to: 'details#homepage'
resources :details, :particulars

  
 
end

app/models/detail.rb
class Detail < ActiveRecord::Base

validates :to, presence: true
validates :from , presence: true
validates :billno, presence: true
validates_numericality_of :billno, on: :create


end

app/models/particular.rb
class Particular < ActiveRecord::Base
	validates :itemname ,:quantity,:rate,presence:true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def showlast

		
		@showl=Detail.last
end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

	def homepage
	end
 
 	
	def new
		@detail=Detail.new
	end

	def create
		@detail=Detail.create(params.require(:detail).permit(:from,:to,:billno,:invoicedate,:duedate))
		if @detail.save 
			redirect_to new_particular_path
		else 
			render new_detail_path
		end
	end

	def index
		@details=Detail.all
	end


	def show
		@count=Detail.count
		@count1=Detail.all.count
		@detail= Detail.find(params[:id])
	end

	def showpdf

	@showdetail=Detail.last
	respond_to do |format|
    format.html
    format.pdf do
       render :pdf => "file_name" ,template: 'details/showpdf.html.erb'
      end
    end

	end

	

	


end

app/controllers/particulars_controller.rb
class ParticularsController < ApplicationController
  before_action :set_particular, only: [:show, :edit, :update, :destroy]

  # GET /particulars
  # GET /particulars.json
  def index
    @particulars = Particular.all
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "file_name" ,template: 'particulars/index.html.erb'
      end
    end
end

# web page to generate the pdf file
def pdfindex
   @particulare = Particular.all
    respond_to do |format|
      format.html #generate html format 
      format.pdf do  #generate the pdf format  web url must end with .pdf format
        render :pdf => "file_name" ,template: 'particulars/pdfindex.html.erb'
        

      end
    end

  end

  # GET /particulars/1
  # GET /particulars/1.json
  def show  # for displaying single item with an id 
      unless @particular.quantity.nil? && @particular.rate.nil?
      @amount=(@particular.quantity)*(@particular.rate)
    end

end

  # GET /particulars/new
  def new
    @particular = Particular.new
  end

  # GET /particulars/1/edit
  def edit
  end

  # POST /particulars
  # POST /particulars.json
  def create
    @particular = Particular.new(particular_params)

    respond_to do |format|
      if @particular.save
        format.html { redirect_to particulars_path, notice: 'New item added successfully.' }
        format.json { render :show, status: :created, location: @particular }
      else
        format.html { render :new }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /particulars/1
  # PATCH/PUT /particulars/1.json
  def update
    respond_to do |format|
      if @particular.update(particular_params)
        format.html { redirect_to @particular, notice: 'Particular was successfully updated.' }
        format.json { render :show, status: :ok, location: @particular }
      else
        format.html { render :edit }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /particulars/1
  # DELETE /particulars/1.json
  def destroy
    @particular.destroy
    respond_to do |format|
      format.html { redirect_to particulars_url, notice: 'Particular was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #private method for extra security 
    def set_particular
      @particular = Particular.find(params[:id])
    end

    # whitelisting the parameter and only allowing the parameters required
    # in rails 4
    def particular_params
      params.require(:particular).permit(:itemname, :quantity, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/particulars_helper.rb
module ParticularsHelper
end

app/views/details/homepage.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Online invoicing system</h1>
		<p>Always free</p>
		<p>Generate beautiful invoices ...</p>
		<p>Generate in pdf format</p>
		<p>Download in pdf</p>
		
		<p>
			<%= link_to("Get started" , new_detail_path, class: "btn btn-primary" ) %> 
		</p>
	</div>
</div>

app/views/details/index.html.erb
<div class="container" style="margin-top:60px;">
	<h1>
		Every data entered is shown below
	</h1>

	<% if @a==0 %>
	0 records found
	<% end %>

</div>




<div class="container col-md-6 col-md-offset-1" style="border: 1px solid #e3e3e3">
	<div class="container col-md-5 col-md-offset-2" >
		<h2 class="text-success">Invoice details</h2>
		<% @details.each do |d| %>

		<p>	<span class="text-info">From: </span><%= d.from%></p>
		<p><span class="text-info">To: </span><%= d.to %></p>
		<p><span class="text-info">Bill no: </span><%= d.billno %></p>
		<p><span class="text-info">Invoice date: </span><%= d.invoicedate %></p>
		<p><span class="text-info">Due date: </span><%= d.duedate %></p>
	</br>
	<% end %>

</div>

</div>

app/views/details/new.html.erb
<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-md-offset-2" style="margin-top:100px;border: solid #e3e3e3 1px;">
	<div class="container">


		<h1>New Details</h1>

		<%= form_for @detail do |f| %>
		<p>
			From address
			<%= f.text_area :from %>
		</p>


		<p>
			To address
			<%= f.text_area :to %>
		</p>

		<p>
			Billno
			<%= f.text_field :billno %>
		</p>	

		<p>
invoice date
			<%= f.date_select :invoicedate %>
		</p>

		<p>
		Due date

			<%= f.date_select :duedate %>
		</p>

		<p> <%= f.submit "save and Next" ,class: "btn btn-primary btn-lg" %> </p>

		<% end %>


	</br>

</div>
</div>


<div class="flash">
	<div class="col-md-2 col-md-offset-0" style="margin-top:120px;">
		<% if @detail.errors.any? %>

		<div id="error_explanation">
			<span class="text-danger"><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</span>

			<ul>
				<% @detail.errors.full_messages.each do |message| %>
				<li class="text-danger"> <%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

	</div>
</div>

app/views/details/show.html.erb
<div class="container" style="margin-top:50px;">

	
	<h1> Details form </h1>
	<p> Serial No: <%= @count %> </p>
	<p>
		TO:<%= @detail.to %>
	</p>

	<p>
		from:<%=@detail.from %>
	</p>

	<p>
		billno:<%= @detail.billno %>
	</p>

	<p>
		invoice created at:  <%=@detail.invoicedate %>
	</p>

	<p>
		due date :  <%= @detail.duedate %>
	</p>

	<%= link_to("<< Return to Homepage", root_path ) %>
	
</div>

app/views/details/showlast.html.erb
<div class="container" style="margin-top:50px;">

	
	<h1> Details form </h1>
	
	<p>
		TO:<%= @showl.to %>
	</p>

	<p>
		from:<%=@showl.from %>
	</p>

	<p>
		billno:<%= @showl.billno %>
	</p>

	<p>
		invoice created at:  <%=@showl.invoicedate %>
	</p>

	<p>
		due date :  <%= @showl.duedate %>
	</p>

	<%= link_to("<< Return to Homepage", root_path ) %>
	
</div>

app/views/details/showpdf.html.erb
<div class="container" style="margin-top:50px;">

	
	<h1> Details </h1>
	
	<p>
		TO:<%= @showdetail.to %>
	</p>

	<p>
		from:<%=@showdetail.from %>
	</p>

	<p>
		billno:<%= @showdetail.billno %>
	</p>

	<p>
		invoice created at:  <%=@showdetail.invoicedate %>
	</p>

	<p>
		due date :  <%= @showdetail.duedate %>
	</p>

	
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsinvoice1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<a class="navbar-brand" href="#">Invoice Generator</a>
	<ul class="nav navbar-nav">
		<li class="active">
			
			<%= link_to("Home", root_path ) %>
		</li>
		
	</ul>
</nav>



<div class="container" style="margin-top:60px;">
	<h1>
		
	</h1>

	<% if @a==0 %>
	0 records found
	<% end %>

</div>




  

<%= yield %>

</body>
</html>

app/views/layouts/showlast.html.erb
<div class="container" style="margin-top:50px;">

	
	<h1> Details form </h1>
	
	<p>
		TO:<%= @showl.to %>
	</p>

	<p>
		from:<%=@showl.from %>
	</p>

	<p>
		billno:<%= @showl.billno %>
	</p>

	<p>
		invoice created at:  <%=@showl.invoicedate %>
	</p>

	<p>
		due date :  <%= @showl.duedate %>
	</p>

	<%= link_to("<< Return to Homepage", root_path ) %>
	
</div>

app/views/particulars/_form.html.erb
<div class="conatiner" style="margin-top: 10px;">
  
<%= form_for(@particular) do |f| %>
  <% if @particular.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@particular.errors.count, "error") %> prohibited this particular from being saved:</h2>

      <ul>
      <% @particular.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.label :itemname %> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= f.label :quantity %>  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= f.label :rate %> </br>
    <%= f.text_field :itemname ,placeholder: "Item Name" %>


    <%= f.number_field :quantity , placeholder: 'Number of items'%>
 
 
    
    RM <%= f.number_field :rate,:placeholder => " Ringgit" %>

  
  <div class="actions" style="margin-top: 20px;">
    <%= f.submit "create" ,class: "btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/particulars/edit.html.erb
<div class="container" style="margin-top: 100px;">
	
<h1>Editing Particular</h1>

<%= render 'form' %>

<%= link_to 'Show', @particular %> |
<%= link_to 'Back', particulars_path %>
</div>

app/views/particulars/index.html.erb
<%= wisepdf_stylesheet_tag "bootstrap.min" %>
<div class="container" style="margin-top: 100px;">
  <p id="notice" ><%= notice %></p>

  <div class="container col-md-8 col-md-offset-1" style="border: 1px solid #e3e3e3">
    
    <h1 style="margin-left: 20px;">Items</h1>

    <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
      <table class="table table-hover">
        <thead>
          <tr class="bg-primary">
            <th>Item Name</th>
            <th>Quantity </th>
            <th>Rate</th>
            <th>Amount</th>
            <th>action</th>
            <th>action</th>

          </tr>
        </thead>
        <tbody>
         <tbody>
          <% @particulars.each do |particular| %>
          <tr>
            <td><%= particular.itemname %></td>
            <td><%= particular.quantity %></td>
            <td>RM <%= particular.rate %></td>
            <td>RM <%= particular.quantity * particular.rate %></td>


            <td><%= link_to 'Edit', edit_particular_path(particular) , class: "text-danger" %></td>
            <td><%= link_to 'Remove', particular, class: "text-danger",method: :delete, data: { confirm: 'Are you sure?' }%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Add New Item', new_particular_path , class: "btn btn-sm btn-default" %>
      <%= link_to 'Generate pdf', particulars_pdfindex_path(format: 'pdf') , class: "btn btn-sm btn-success" %>

      <%= link_to 'Generate pdf details', details_showpdf_path(format: 'pdf') , class: "btn btn-sm btn-success" %>
    </div>

  </div>
  <div class="col-md-4 col-md-offset-4">
  
</div>

 
 

app/views/particulars/new.html.erb
<div class="container" style="margin-top:100px;">

<h1>Add items</h1>

<%= render 'form' %>

</div>

app/views/particulars/pdfindex.html.erb
<%= wisepdf_stylesheet_tag "bootstrap.min" %>



<div class="container" style="margin-top: 100px;">
  <p id="notice" ><%= notice %></p>

  <div class="container col-md-8 col-md-offset-1" style="border: 1px solid #e3e3e3">


    <h1 style="margin-left: 20px;">Items</h1>

    <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
      <table class="table table-hover">
        <thead>
          <tr class="bg-primary">
            <th>Item Name</th>
            <th>Quantity </th>
            <th>Rate</th>
            <th>Amount</th>
            

          </tr>
        </thead>
        <tbody>
         <tbody>
          <% @particulare.each do |particular| %>
          <tr>
            <td><%= particular.itemname %></td>
            <td><%= particular.quantity %></td>
            <td>RM <%= particular.rate %></td>
            <td>RM <%= particular.quantity * particular.rate %></td>


            
            
          </tr>
          <% end %>
        </tbody>
      </table>
     
    </div>
  </div>

app/views/particulars/show.html.erb
<div class="container" style="margin-top: 100px;">
	

<p id="notice"><%= notice %></p>


  <strong>Itemname:</strong>
  <%= @particular.itemname %>

&nbsp&nbsp&nbsp


  <strong>Quantity:</strong>
  <%= @particular.quantity %>
&nbsp&nbsp&nbsp




  <strong>Rate:</strong>
  <%= @particular.rate %>
&nbsp&nbsp&nbsp&nbsp


  <strong>Amount</strong>
  <%= @amount %>
  &nbsp&nbsp&nbsp

<%= link_to 'Edit', edit_particular_path(@particular) %> |
<%= link_to 'Back', particulars_path %>
<%= link_to 'New', new_particular_path %>
</div>

app/views/shared/_deindex.html.erb
<div class="container" style="margin-top:60px;">
	<h1>
		Every data entered is shown below
	</h1>

	<% if @a==0 %>
	0 records found
	<% end %>

</div>

<div class="container col-md-6 col-md-offset-1" style="border: 1px solid #e3e3e3">
	<div class="container col-md-5 col-md-offset-2" >
		<h2 class="text-success">Invoice details</h2>
		<% @details.each do |d| %>

		<%= render d %>
	<% end %>

</div>

</div>